version: 2
orbs:
    codecov: codecov/codecov@1.0.2
jobs:
    build:
        machine:
            - COVERALLS_PARALLEL: true
        docker:
            - image: circleci/node:lts-browsers
              environment:
                  JOBS: 1

        steps:
            - checkout
            - run:
                  name: Yarn Install
                  command: yarn install --non-interactive
            - run:
                  name: Run JS Lint
                  command: yarn run lint:js
            - run:
                  name: Run Tests
                  command: yarn test
        steps:
        - codecov/upload:
            file: app/coverage
