version: 2
jobs:
    build:
        docker:
            - image: circleci/node:chakracore-10.13
              environment:
                  JOBS: 2
        wworking_directory: ~/app
        steps:
            - checkout
            - run:
                  name: Yarn Install
                  command: yarn install --non-interactive
            - run:
                  echo 'export PATH=~/gitzoom-web/node_modules/.bin:$PATH' >>
                  $BASH_ENV
            - run:
                  name: Run JS Lint
                  command: yarn run lint:js
            - run:
                  name: Run Tests
                  command: yarn test
            - deploy:
                  command: |
                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        ember deploy production
                      fi
